### PR TITLE
Support non-square grids

### PR DESCRIPTION
**Pull request by rolopogo**
Required (check [ ] -> [x] all that apply):

- [ ] There is a relevant & reviewed issue in the tracker (please link it below)
- [ x ] I've followed all instructions that were given in the issue comments (if not, please specify below)
- [ x ] This PR only resolves a single issue. (Please split up bigger PRs into multiple requests where needed.)
- [ x ] To the best of my ability I've followed good commit hygiene, avoided fixing too many things per commit, provided good commit messages, and did basic cleaning on the commit history if needed.
- [ x ] I am willing and able to release this contribution under the MIT license (if not, please explain below)
- [ x ] I have described this PR, highlighting important files, additional changes, and what you expect would be most important to review.
- [ ] If relevant, provide example projects and tests for the unit tester

See https://github.com/david-pfx/PuzzleScriptNext/issues/119

Adds new state property cell_height, set to B when defining ``sprite_size AxB``
Adjusts sprite rendering, default sprites, and grid layout when used.

### CODE REVIEW

**Comment by david-pfx** [comment]
Looks good. I'd like to merge it as a branch PR#121 so I can review and test locally before adding it to master, and I can't see how to do that.

**Comment by david-pfx** [comment]
Two problems. 
* A compile/merge error in graphics.js@584
*  Hebird does not work correctly. Better, but not right.

**Comment by rolopogo** [comment]
Can you link to hebird so I can test it locally, then I will have another pass.

**Comment by david-pfx** [comment]
Hebird:
https://clementsparrow.github.io/Pattern-Script/src/play.html?p=5ddd0569697361191ae5211cdd5b65fa

**Comment by david-pfx** [comment]
Manually merged with minor tweaks. Thanks.

**Pull request closed without merging**
