### PR TITLE
fix: issue 3 - Glyph count now returned every element from the legend…

### PR DESCRIPTION
**Pull request by maximyzer**
… and not only the ones defined by a single character

Required (check [ ] -> [x] all that apply):

- [ x] There is a relevant & reviewed issue in the tracker (please link it below)
- https://github.com/david-pfx/PuzzleScriptNext/issues/3
- [x ] I've followed all instructions that were given in the issue comments (if not, please specify below)
- x[ ] This PR only resolves a single issue. (Please split up bigger PRs into multiple requests where needed.)
- [ x] To the best of my ability I've followed good commit hygiene, avoided fixing too many things per commit, provided good commit messages, and did basic cleaning on the commit history if needed.
- [x ] I am willing and able to release this contribution under the MIT license (if not, please explain below)
- [ x] I have described this PR, highlighting important files, additional changes, and what you expect would be most important to review.
- [x ] If relevant, provide example projects and tests for the unit tester

### CODE REVIEW

**Comment by maximyzer** [comment]
Changed my PR to fix line 977.

Now the editor behaves like it used to in PS and PS Plus.

Level : 
image

Level only 4 tiles wide : 
image

**Comment by david-pfx** [comment]
OK, now I get it. My changes used `screenwidth` without the +2, so the fix is correct. I missed it, and didn't notice the changed result.
But why the other change? `GlyphCount()` is only used by the mouse wheel. I guess that's a different (but related) bug, and I didn't do that one. I'll have to take a look at this one.

**Comment by maximyzer** [comment]
Yeah it's different bug now since it's only used somewhere else. 
Basically, without this the scroll wheel can scroll through glyphs that are not rendered and you can lose the selector.

**Comment by david-pfx** [comment]
I see the issue and I see how it arose. The `screenwidth+1` is my bug, the other one is presumably from PS+. But I'm having trouble reproducing it. See
`https://www.puzzlescript.net/editor.html?demo=dreizack`
`https://david-pfx.github.io/PuzzleScriptNext/src/editor.html?demo=dreizack`
This change isn't going to make these the same.

**Comment by maximyzer** [comment]
Do you want me to remove the glyphcount() change and file a separate bug ?

I tried loading this `https://david-pfx.github.io/PuzzleScriptNext/src/editor.html?demo=dreizack`
but if I do CTRL+A to copy the code, the editor freezes

**Comment by david-pfx** [comment]
Sorry about this, really. I think the problem is that I've deployed the non-compiled version, and I think it's mostly due to being really really slow. I need to deploy the compiled version, and so far I can't find out how to do that.

**Comment by maximyzer** [comment]
No trouble, we'll figure it out :)

**Comment by maximyzer** [comment]
Looks like the `screenwidth+1` should be merged back in base puzzlescript imo

**Comment by david-pfx** [comment]
The glyph count for the wheel is dead simple. It was easy to repro, already fixed.

The editor rows -1 is a new bug, not in PS, but I need a repro test (a program that shows it), and it doesn't seem to explain all the difference in appearance. Your fix is needed, but it may not be all.

**Comment by maximyzer** [comment]
Just like that, are you fine with chatting here or would you prefer something like discord to share stuff a bit faster ?

I tested the row thing in base puzzle script and I had the same bugged behaviour :
image

**Comment by david-pfx** [comment]
Thanks for raising these issues. For now, I'm going to close the issues and the PRs and apply changes by hand. Please check out the next release and raise another issue as needed. If you do, please supply a repro case: preferably one of the standard demo programs that shows the problem.

Yes, I think these problems exist in both PS and PS+, and possibly P:S as well. Up to you.

**Comment by david-pfx** [comment]
Re chat: PuzzleScript is on the thinky-puzzle-games server on Discord, and there is a PSNext thread. Good place to chat.

You don't seem to be on. Do you need an invite?

**Comment by maximyzer** [comment]
Found the discord, I'll be able to chat there soon, there's a 10 minutes buffer on new users

**Pull request closed without merging**
